HEADERS_DELIVERY_POINT_ADDRESS = [
    "record_identifier",
    "change_type",
    "pro_order",
    "uprn",
    "parent_addressable_uprn",
    "rm_udprn",
    "organisation_name",
    "department_name",
    "sub_building_name",
    "building_name",
    "building_number",
    "dependent_thoroughfare_name",
    "thoroughfare_name",
    "double_dependent_locality",
    "dependent_locality",
    "post_town",
    "postcode",
    "postcode_type",
    "welsh_dependent_thoroughfare_name",
    "welsh_thoroughfare_name",
    "welsh_double_dependent_locality",
    "welsh_dependent_locality",
    "welsh_post_town",
    "po_box_number",
    "process_date",
    "start_date",
    "end_date",
    "last_update_date",
    "entry_date",
]


HEADERS_BLPU = [
    "record_identifier",
    "change_type",
    "pro_order",
    "uprn",
    "logical_status",
    "blpu_state",
    "blpu_state_date",
    "parent_uprn",
    "x_coordinate",
    "y_coordinate",
    "rpc",
    "local_custodian_code",
    "start_date",
    "end_date",
    "last_update_date",
    "entry_date",
    "postal_address",
    "postcode_locator",
    "multi_occ_count",
]


HEADERS_CLASSIFICATION = [
    "record_identifier",
    "change_type",
    "pro_order",
    "uprn",
    "class_key",
    "classification_code",
    "class_scheme",
    "scheme_version",
    "start_date",
    "end_date",
    "last_update_date",
    "entry_date",
]


HEADERS_LPI = [
    "record_identifier",
    "change_type",
    "pro_order",
    "uprn",
    "lpi_key",
    "language",
    "logical_status",
    "start_date",
    "end_date",
    "last_update_date",
    "entry_date",
    "sao_start_number",
    "sao_start_suffix",
    "sao_end_number",
    "sao_end_suffix",
    "sao_text",
    "pao_start_number",
    "pao_start_suffix",
    "pao_end_number",
    "pao_end_suffix",
    "pao_text",
    "usrn",
    "usrn_match_indicator",
    "area_name",
    "level",
    "official_flag",
]


HEADERS_ORGANIZATION = [
    "record_identifier",
    "change_type",
    "pro_order",
    "uprn",
    "org_key",
    "organisation",
    "legal_name",
    "start_date",
    "end_date",
    "last_update_date",
    "entry_date",
]


HEADERS_APPLICATION_CROSS_REFERENCE = [
    "record_identifier",
    "change_type",
    "pro_order",
    "uprn",
    "xref_key",
    "cross_reference",
    "version",
    "source",
    "start_date",
    "end_date",
    "last_update_date",
    "entry_date",
]


HEADERS_STREET = [
    "record_identifier",
    "change_type",
    "pro_order",
    "usrn",
    "record_type",
    "swa_org_ref_naming",
    "state",
    "state_date",
    "street_surface",
    "street_classification",
    "version",
    "street_start_date",
    "street_end_date",
    "last_update_date",
    "record_entry_date",
    "street_start_x",
    "street_start_y",
    "street_end_x",
    "street_end_y",
    "street_tolerance",
]


HEADERS_STEET_DESCRIPTOR = [
    "record_identifier",
    "change_type",
    "pro_order",
    "usrn",
    "street_description",
    "locality_name",
    "town_name",
    "administrative_area",
    "language",
]


HEADERS_SUCCESSOR = [
    "record_identifier",
    "change_type",
    "pro_order",
    "uprn",
    "succ_key",
    "start_date",
    "end_date",
    "last_update_date",
    "entry_date",
    "successor",
]